FROM node:lts-alpine

WORKDIR /app

# Copy package.json และ package-lock.json
COPY package*.json ./

# ติดตั้ง dependencies
RUN npm install

# Copy source code ทั้งหมด
COPY . .

# กำหนด environment variable (ค่า default)
ENV NODE_ENV=development
ENV PORT=4000

# เปิดพอร์ต
EXPOSE 4000

# คำสั่งเริ่มรัน
CMD ["npm", "run" , "dev"]